env: "local"
database:
  host: localhost
  port: 5432
  name: user_base
  user: postgres
  password: root
http_server:
  address: "localhost:8081"
  timeout: 4s
  idle_timeout: 60s
jwt:
  secret_key: fdhjaskhHASUSDFGHUGUhsdfgj312HJFldshUl
redis_database:
  addr: "localhost:6379"