env: "local"
database:
  host: localhost
  port: 5432
  name: book_base
  user: postgres
  password: 1977
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
jwt:
  secret_key: fdhjaskhHASUSDFGHUGUhsdfgj312HJFldshUl